insert into item(price,name) VALUES(10.00,"Jerk Chicken");
insert into item(price,name) VALUES(12.00,"Goat");
insert into item(price,name) VALUES(9.00,"Pasta");
insert into item(price,name) VALUES(12.00,"Seafood Pasta");
insert into item(price,name) VALUES(13.00,"Oxtail");
insert into item(price,name) VALUES(1.50,"1 Pork Egg Roll 1 Pc");
insert into item(price,name) VALUES(5.75,"3 Roast Pork");
insert into item(price,name) VALUES(1.50,"2 Shrimp Egg Roll 1 Pc");
insert into item(price,name) VALUES(7.50,"4 Bar B Q Spare Ribs");
insert into item(price,name) VALUES(3.50,"5 Fried Wontons 10 Pcs");
insert into item(price,name) VALUES(4.25,"6 Cheese Wontons 8 Pcs");
insert into item(price,name) VALUES(5.50,"7 Fried or Steamed Dumplings 8 Pcs");
insert into item(price,name) VALUES(4.00,"8 Fried Onion Rings 20 Pcs");
insert into item(price,name) VALUES(1.50,"9 Fantail Jumbo Shrimp");
insert into item(price,name) VALUES(4.00,"10 Fried Apple Sticks 20 Pcs");
insert into item(price,name) VALUES(5.00,"11 Sugar Biscuits 10 Pcs");
insert into item(price,name) VALUES(2.00,"12 French Fries");
insert into item(price,name) VALUES(4.00,"13 Fried Yellow Plantain");
insert into item(price,name) VALUES(4.00,"13 Fried Green Plantain");
insert into item(price,name) VALUES(7.00,"14 Boneless B B Q Spare Ribs");
insert into item(price,name) VALUES(2.50,"15 Egg Wonton Mix Soup");
insert into item(price,name) VALUES(2.00,"16 Egg Drop Soup");
insert into item(price,name) VALUES(2.00,"18 Chicken Rice Soup");
insert into item(price,name) VALUES(2.00,"17 Chicken Noodle Soup");
insert into item(price,name) VALUES(2.00,"19 Wonton Soup");
insert into item(price,name) VALUES(5.00,"20 Yat Gaw Mein Quart");
insert into item(price,name) VALUES(5.25,"21 Yat Gaw Mein Quart");
insert into item(price,name) VALUES(3.00,"22 Hot and Sour Soup");
insert into item(price,name) VALUES(4.00,"23 Chinese Vegetables with Bean Curd Soup Quart");
insert into item(price,name) VALUES(6.00,"24 Seafood Soup Quar");